server:
  host: "0.0.0.0"
  port: 8081
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  max_header_bytes: 1048576

rate_limit:
  enabled: true
  qps: 50
  burst: 100

log:
  level: "info"
  encoding: "json"
  output_paths: ["stdout"]
  error_output_paths: ["stderr"]

worker_pool:
  workers: 8
  queue_size: 32

llm_configs:
  local:
    api_base_url: "http://localhost:3000/v1"
    api_key: "sk-rac1XoSpt3eESULMNGKxAvBQq2WwcqIoSJMhsg2ubOU6tiJQ"
    model: "glm-4.5"
