server:
  host: "0.0.0.0"
  port: 8081
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  max_header_bytes: 1048576

rate_limit:
  enabled: true
  qps: 50
  burst: 100

log:
  level: "info"
  encoding: "json"
  output_paths: ["stdout"]
  error_output_paths: ["stderr"]

worker_pool:
  workers: 8
  queue_size: 32

# 租户配置
tenant:
  required: true  # 是否要求租户头部
  exclude_paths:  # 不需要租户验证的路径
    - "^/health$"
    - "^/api/workflows$"

# CORS配置
cors:
  enabled: true
  allowed_origins:  # 允许的域名列表
    - "http://localhost:5173"  # 前端开发环境
    - "http://localhost:3000"  # 备用前端端口
    # 生产环境示例:
    # - "https://yourdomain.com"
    # - "https://app.yourdomain.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT" 
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-User-ID"      # 租户用户ID
    - "X-Archive-ID"   # 租户档案ID
  exposed_headers: []
  allow_credentials: false
  max_age: 86400  # 预检请求缓存时间(秒)

llm_configs:
  local:
    api_base_url: "http://localhost:3000/v1"
    api_key: "sk-xxx"
    model: "glm-4.5"
